### ISSUE TITLE
Having difficulty knowing how to set up the GitHub App

### ISSUE THREAD

**Issue by bastienboutonnet** [imjohnbo/ok-to-test#12]
Hi there,

Thanks a lot for creating this, this looks really nice and exactly what I need. I understand pretty much everything regarding the workflow part of things but I'm struggling to know what kind of parameters to put in when creating the github app even when following URL: https://docs.github.com/en/free-pro-team@latest/developers/apps/creating-a-github-app

Especially not sure what to put in the URL sections as well as what kind of permissions it will need. 

Do you have more info on how to do this best?

**Comment by imjohnbo** [comment]
Hi @bastienboutonnet, thanks for the question. 

The only permissions you should need are documented here: https://github.com/imjohnbo/ok-to-test#authentication. I believe all other fields can be filled out as you wish. Remember to [install the GitHub App after it is created](https://github.com/imjohnbo/ok-to-test#setup) and save GitHub repository secrets accordingly. 😺
