### ISSUE TITLE
Unhandled error: TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by knelasevero** [imjohnbo/ok-to-test#14]
Hey! Can you help me debug what is happening with the actions/github-script@v5 step on my CI?

https://github.com/external-secrets/external-secrets/runs/4166526723?check_suite_focus=true

We are basically following the same pattern suggested here in this repo. But out of nowhere this started to break. I just tried changing `await github.pulls.get` to `await github.pull_requests.get` but of course it wasn't it :sweat_smile: 

How did you figure out what to include in this script?

**Comment by imjohnbo** [comment]
Hi @knelasevero! Sorry I missed this!

Would you let me know if https://github.com/imjohnbo/ok-to-test/commit/474c02cafe14327d1a60febb7eb375f5935a430e fixed the issue? 🙏 I think the upstream octokit dependency changed the way `rest` calls are made.

**Comment by alekc** [comment]
Hi @imjohnbo, just hit the same issue with the latest master version. 
https://github.com/alekc/terraform-provider-auth0/runs/4437185144?check_suite_focus=true

This is my pipeline
```
- uses: actions/github-script@v5
        id: update-check-run
        if: ${{ always() }}
        env:
          number: ${{ github.event.client_payload.pull_request.number }}
          job: ${{ github.job }}
          # Conveniently, job.status maps to https://developer.github.com/v3/checks/runs/#update-a-check-run
          conclusion: ${{ job.status }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pull } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: process.env.number
            });
            const ref = pull.head.sha;
            const { data: checks } = await github.rest.checks.listForRef({
              ...context.repo,
              ref
            });
            const check = checks.check_runs.filter(c => c.name === process.env.job);
            const { data: result } = await github.rest.checks.update({
              ...context.repo,
              check_run_id: check[0].id,
              status: 'completed',
              conclusion: process.env.conclusion
            });
            return result;
```

And this is the error message:
```
(node:30469) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
TypeError: Cannot read property 'id' of undefined
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4942:56), <anonymous>:13:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4997:20)
Error: Unhandled error: TypeError: Cannot read property 'id' of undefined
```

**Comment by imjohnbo** [comment]
Hi @alekc, that's a different error message that I believe is caused by your [job name ](https://github.com/alekc/terraform-provider-auth0/actions/runs/1546929389/workflow#L49) being different than your [check run name](https://github.com/alekc/terraform-provider-auth0/actions/runs/1546929389/workflow#L50), which causes `check` on [this line](https://github.com/alekc/terraform-provider-auth0/actions/runs/1546929389/workflow#L110) to equal an empty array. 

Since `actions/github-script` is "just" JS, I'd recommend debugging with some `console.log` statements. Another approach could be updating the check run status with the [GitHub CLI](https://github.com/cli/cli) using `gh api`. Good luck!
