### ISSUE TITLE
Is the trusted action template vulnerable with a merge from the upstream repository?

### ISSUE THREAD

**Issue by adamint** [imjohnbo/ok-to-test#18]
Specifically, here:
`if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository`
in the template for a trusted action - wouldn't this be true if the forked repository's PR last commit was a merge from the upstream repository into the forked repo?

**Comment by imjohnbo** [comment]
👋 Thanks for the question. I just [double checked](https://github.com/imjohnbo/ok-to-test/actions/runs/2786340342) and I can't think of anything – even that situation - that would cause the repo name of the incoming PR (`github.event.pull_request.head.repo.full_name`) to change to the name of the base repo (`github.repository`). A commit to a repository doesn't relate to the repository's name. 

Hope that helps, and let me know if you see something different!
