### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by hamelsmu** [imjohnbo/ok-to-test#2]
Why invoke a repo dispatch event? Can’t we instead open a check run from the issue_comment event directly?  Would something like this work:

If owner OR comment = “/ok-to-test”
...tests?

Thanks just learning I’m obviously missing something

**Comment by imjohnbo** [comment]
> Would something like this work:

> If owner OR comment = “/ok-to-test”
.> ..tests?

Good question @hamelsmu – yes! I was envisioning more slash commands like `deploy` being parsed in a separate workflow (now called [`ok-to-test.yml`](https://github.com/imjohnbo/ok-to-test/blob/02903c45e6a36ca82c7d68456571f9601b355879/.github/workflows/ok-to-test.yml)). It's a tradeoff of complexity, which is now hidden behind the helper action(s) in [`ok-to-test.yml`](https://github.com/imjohnbo/ok-to-test/blob/02903c45e6a36ca82c7d68456571f9601b355879/.github/workflows/ok-to-test.yml).

`peter-evans/slash-command-dispatch` takes care of a few other things that I'd want to see in a test-centric solution, like reacting back on the comment, ensuring the permission level of the commenter, restricting the issue type, and grabbing the pull request number that [the test workflow can use](https://github.com/imjohnbo/ok-to-test/blob/02903c45e6a36ca82c7d68456571f9601b355879/.github/workflows/integration.yml#L33).

Maybe we should make this into a stop/go action that takes an `issue_comment`, decides if it's a valid comment from a permissioned author, and proceeds. 🤔This part to update the PR check could also be a separate action: https://github.com/imjohnbo/ok-to-test/blob/02903c45e6a36ca82c7d68456571f9601b355879/.github/workflows/integration.yml#L40-L71.
